
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: shopuser
    password: shoppass
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 50

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-this-in-prod}
    issuer: ${APP_JWT_ISSUER:orders-inventory-service}
    expiration-minutes: ${APP_JWT_EXPIRATION_MINUTES:60}


logging:
  level:
    root: INFO
    com.example.shop: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %logger{36} [%X{correlationId} %X{user} %X{orderId}] - %msg%n"

